# Generated by Django 4.1.7 on 2023-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_travertin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travertin',
            name='image',
            field=models.ImageField(upload_to='KeramaStone/KeramaStone/MainApp/static/images/products/travertin', verbose_name='Прикрепите изображение'),
        ),
    ]
