# Generated by Django 4.1.7 on 2023-03-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_travertin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travertin',
            name='image',
            field=models.ImageField(upload_to='static/images/products/travertin/', verbose_name='Прикрепите изображение'),
        ),
    ]
