# Generated by Django 4.1.7 on 2023-03-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_travertin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя: ')),
                ('phone_number', models.CharField(max_length=21, verbose_name='Номер телефона: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта: ')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания: ')),
            ],
        ),
        migrations.AddField(
            model_name='travertin',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='travertin',
            name='not_available',
            field=models.BooleanField(default=False, verbose_name='Нет в наличии'),
        ),
        migrations.AddField(
            model_name='travertin',
            name='order_only',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
    ]
