# Generated by Django 4.1.7 on 2023-03-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_request_travertin_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='text_box',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
