# Generated by Django 4.1.7 on 2023-04-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_request_created_at_alter_request_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travertin',
            name='not_available',
        ),
        migrations.AddField(
            model_name='granit',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='granit',
            name='is_custom_order',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
        migrations.AddField(
            model_name='mramor',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='mramor',
            name='is_custom_order',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
        migrations.AlterField(
            model_name='granit',
            name='image',
            field=models.ImageField(upload_to='static/images/products/granit/', verbose_name='Прикрепите изображение'),
        ),
        migrations.AlterField(
            model_name='mramor',
            name='image',
            field=models.ImageField(upload_to='static/images/products/mramor/', verbose_name='Прикрепите изображение'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания: '),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта: '),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя: '),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=21, verbose_name='Номер телефона: '),
        ),
        migrations.AlterField(
            model_name='request',
            name='text_box',
            field=models.TextField(),
        ),
    ]
